### ISSUE TITLE
Application crash attempting to change fonts after selecting text with multiple fonts

### ISSUE THREAD

**Issue by bjaudon** [bjaudon/PrestigeEdit#7]
System.NullReferenceException: Object reference not set to an instance of an object when selecting text with multiple fonts, which causes the font style and font size combos to blank. When picking a new font, this crash is referenced. Similar to issue #4

**Comment by bjaudon** [comment]
Significant performance issues exist when parsing each character in the file to apply the font changes. I believe this is due to the use of interfaces and referencing the control through a different class. 

Considering disabling the Font Family and Font size combo boxes as well as the style buttons to prevent this until a solution with much better performance can be realized. 

For a 500 word document, it took nearly 30 seconds to step through each character and apply the new font styling which is unacceptable.

**Comment by bjaudon** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at PrestigeEdit.Form1.toolStripComboBoxFont_SelectionChangeCommitted(Object sender, EventArgs e) in C:\Users\bjaudon\source\repos\PrestigeEdit\PrestigeEdit\Form1.cs:line 310
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectionChangeCommitted(EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectionChangeCommittedInternal(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bjaudon** [comment]
Pretty sure I am hitting this (https://github.com/dotnet/runtime/issues/7291). Seems to be a JIT compiler optimization problem.

**Comment by bjaudon** [comment]
Pretty sure I am hitting dotnet runtime issue 7291.

**Comment by bjaudon** [comment]
https://github.com/bjaudon/PrestigeEdit/commit/dba1f9477f01a73bce2c7e209905469150952267
